# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/i2c_msb_bd/i2c_msb_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==i2c_msb_bd || ORIG_REF_NAME==i2c_msb_bd} -quiet] -quiet

# XDC: bd/i2c_msb_bd/i2c_msb_bd_ooc.xdc
